name: CI

on: [push]

permissions:
  contents: read

jobs:
  build-enabler:
    name: Build the application for enabler
    runs-on: ubuntu-latest
    env:
      CTP_REGION: ${{ secrets.CTP_REGION }}
    defaults:
      run:
        working-directory: enabler
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'

      - name: Install modules
        run: npm ci

  build-processor:
    name: Build the application for processor
    runs-on: ubuntu-latest
    env:
      CTP_REGION: ${{ secrets.CTP_REGION }}
    defaults:
      run:
        working-directory: processor
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Use Node.js 24.x
        uses: actions/setup-node@v7
        with:
          node-version: '24.x'

      - name: Install modules
        run: npm ci